// frontend/src/components/shell/AppSidebar.tsx
"use client";

import {
  BriefcaseBusiness,
  LayoutDashboard,
  Settings,
  Send,
} from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";

const links = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/jobs", label: "Jobs", icon: BriefcaseBusiness },
  { href: "/applications", label: "Applications", icon: Send },
  { href: "/settings", label: "Settings", icon: Settings },
];

export function AppSidebar() {
  const pathname = usePathname();

  return (
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-52 border-r border-base-300 bg-base-100 pt-16 md:block">
      <nav
        className="flex h-full flex-col gap-1 p-3"
        aria-label="Main navigation"
      >
        {links.map(({ href, label, icon: Icon }) => {
          const active = pathname === href || pathname.startsWith(`${href}/`);
          return (
            <Link
              className={`btn justify-start gap-3 ${active ? "btn-primary" : "btn-ghost"}`}
              href={href}
              key={href}
            >
              <Icon className="size-4" aria-hidden="true" />
              {label}
            </Link>
          );
        })}
        <p className="mt-auto px-3 pb-3 text-xs text-base-content/50">
          Your job search workspace
        </p>
      </nav>
    </aside>
  );
}

// frontend/src/lib/components/layout/AppSidebar.svelte
<script lang="ts">
	import AppearanceIconSwitch from '$lib/components/layout/AppearanceIconSwitch.svelte';
	import { page } from '$app/stores';

	const path = $derived($page.url.pathname);

	const linkCls = (href: string) =>
		`block w-full rounded-xl px-3 py-2.5 text-left text-sm font-medium tracking-nav transition-colors ${
			path === href || path.startsWith(href + '/')
				? 'bg-primary text-primary-content'
				: 'text-base-content hover:bg-base-200'
		}`;
</script>

<aside
	class="border-base-300 bg-base-100 flex w-52 shrink-0 flex-col border-r"
	aria-label="Main navigation"
>
	<nav class="flex flex-1 flex-col gap-1 p-3" aria-label="Main">
		<a class={linkCls('/dashboard')} href="/dashboard">Dashboard</a>
		<a class={linkCls('/jobs')} href="/jobs">Jobs</a>
		<a class={linkCls('/applications')} href="/applications">Applications</a>
		<a class={linkCls('/settings')} href="/settings">Settings</a>
	</nav>
	<div class="border-base-300 flex flex-col gap-2 border-t p-3">
		<span class="text-base-content/60 text-xs font-medium tracking-wide uppercase">Appearance</span>
		<AppearanceIconSwitch />
	</div>
</aside>
