// frontend/src/routes/(app)/jobs/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { get } from 'svelte/store';
	import Button from '$lib/components/ui/Button.svelte';
	import CompanyBrief from '$lib/components/jobs/CompanyBrief.svelte';
	import EvaluationPanel from '$lib/components/jobs/EvaluationPanel.svelte';
	import JobDocumentsModal from '$lib/components/jobs/JobDocumentsModal.svelte';
	import { useCreateApplication, useMarkJobNotInterested } from '$lib/hooks/useApplication';
	import {
		useJobEvaluationFromRoute,
		useJobFromRoute,
		useTriggerEvaluation
	} from '$lib/hooks/useJobs';
	import { ApiError } from '$lib/api/errors';
	import { toast } from '$lib/stores/toast';

	const jobId = $derived($page.params.id);

	const jobQ = useJobFromRoute();
	const evQ = useJobEvaluationFromRoute();
	const triggerEv = useTriggerEvaluation();
	const createApp = useCreateApplication();
	const markNotInterested = useMarkJobNotInterested();
	let documentsModalOpen = $state(false);
	const backHref = $derived.by(() => {
		const requested = $page.url.searchParams.get('backTo');
		if (!requested) return '/jobs';
		return requested.startsWith('/jobs') ? requested : '/jobs';
	});

	async function reevaluate(): Promise<void> {
		if (!jobId) return;
		try {
			await get(triggerEv).mutateAsync(jobId);
			toast.info('Evaluation queued — you will get a toast when it completes.');
		} catch (e) {
			toast.error(e instanceof ApiError ? e.message : 'Could not queue evaluation');
		}
	}

	async function generateDocs(): Promise<void> {
		if (!jobId) return;
		try {
			const app = await get(createApp).mutateAsync(jobId);
			await goto(`/jobs/${jobId}/apply?applicationId=${app.id}`);
		} catch (e) {
			if (e instanceof ApiError && e.code === 'application_documents_generating') {
				toast.info(e.message);
				return;
			}
			toast.error(e instanceof ApiError ? e.message : 'Could not create application');
		}
	}

	async function notInterested(): Promise<void> {
		if (!jobId) return;
		try {
			await get(markNotInterested).mutateAsync(jobId);
			toast.success('Marked as not interested.');
			await goto('/jobs');
		} catch (e) {
			toast.error(e instanceof ApiError ? e.message : 'Could not update');
		}
	}
</script>

<svelte:head>
	<title>{$jobQ.data?.title ?? 'Job'} — Kaziro</title>
</svelte:head>

<div class="scroll-region h-full min-h-0 overflow-y-auto pr-1">
	{#if $jobQ.isPending || $evQ.isPending}
		<p class="text-sm text-base-content/60">Loading…</p>
	{:else if $jobQ.isError || $evQ.isError}
		<p class="text-sm text-error">Job or evaluation not found.</p>
	{:else if $jobQ.data && $evQ.data}
		<div class="sticky top-0 z-10 -mx-1 mb-6 bg-base-100/95 px-1 pb-3 pt-1 backdrop-blur">
			<div class="mb-3">
				<a
					href={backHref}
					class="btn btn-ghost btn-sm gap-2 rounded-xl text-base-content/80 hover:text-base-content"
					aria-label="Back to jobs list"
				>
					<svg viewBox="0 0 24 24" fill="none" class="h-4 w-4" aria-hidden="true">
						<path
							d="M15 18L9 12L15 6"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
						></path>
					</svg>
					Back to jobs
				</a>
			</div>
			<div class="flex flex-wrap gap-2">
				<Button onclick={() => reevaluate()} disabled={$triggerEv.isPending}
					>Re-run evaluation</Button
				>
				{#if $evQ.data.application_doc}
					<Button variant="secondary" onclick={() => (documentsModalOpen = true)}>
						View documents
					</Button>
				{:else}
					<Button
						variant="secondary"
						onclick={() => generateDocs()}
						disabled={$createApp.isPending}
					>
						Generate documents
					</Button>
				{/if}
				{#if $evQ.data.final_classification !== 'REJECT'}
					<Button
						variant="outline"
						onclick={() => notInterested()}
						disabled={$markNotInterested.isPending}
					>
						{$markNotInterested.isPending ? 'Updating…' : 'Not interested'}
					</Button>
				{/if}
			</div>
		</div>
		<div class="grid gap-6 lg:grid-cols-2">
			<section class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm">
				<h1 class="text-2xl font-semibold">{$jobQ.data.title}</h1>
				<p class="text-base-content/70">{$jobQ.data.company_name}</p>
				<a
					class="link link-primary mt-2 inline-block text-sm font-medium"
					href={$jobQ.data.application_url}
					target="_blank"
					rel="noopener noreferrer"
				>
					Apply on company site
				</a>
				<h2 class="mt-6 text-sm font-semibold">Description</h2>
				<div
					class="mt-2 max-w-none whitespace-pre-wrap text-sm leading-relaxed text-base-content/80"
				>
					{$jobQ.data.description}
				</div>
			</section>
			<div class="space-y-6">
				<EvaluationPanel evaluation={$evQ.data} />
				<CompanyBrief job={$jobQ.data} />
			</div>
		</div>
		{#if $evQ.data.application_doc && jobId}
			<JobDocumentsModal
				bind:open={documentsModalOpen}
				jobPostingId={jobId}
				applicationId={$evQ.data.application_id ?? ''}
				doc={$evQ.data.application_doc}
			/>
		{/if}
	{/if}
</div>

// frontend/src/app/(app)/jobs/[id]/page.tsx
"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  ExternalLink,
  FileText,
  RefreshCw,
  Send,
  Sparkles,
  X,
} from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { JobDocumentsModal } from "@/components/jobs/JobDocumentsModal";
import {
  getJob,
  markJobNotInterested,
  regenerateDocuments,
  triggerJobEvaluation,
} from "@/lib/api/jobs";
import { useAuthStore } from "@/lib/stores/auth";
import { useToastStore } from "@/lib/stores/toast";

export default function JobDetailPage() {
  const id = String(useParams().id);
  const token = useAuthStore((state) => state.token?.access_token ?? "");
  const pushToast = useToastStore((state) => state.push);
  const queryClient = useQueryClient();
  const [documentsOpen, setDocumentsOpen] = useState(false);
  const job = useQuery({
    queryKey: ["jobs", id],
    queryFn: () => getJob(token, id),
    enabled: Boolean(token && id),
  });
  const action = useMutation({
    mutationFn: async (kind: "evaluate" | "generate" | "dismiss") => {
      if (kind === "evaluate") await triggerJobEvaluation(token, id);
      else if (kind === "generate") await regenerateDocuments(token, id);
      else await markJobNotInterested(token, id);
      return kind;
    },
    onSuccess: (kind) => {
      const message =
        kind === "generate"
          ? "Document generation queued. You will be notified when it is ready."
          : kind === "evaluate"
            ? "Evaluation queued. You will be notified when it is ready."
            : "Job marked as not interested.";
      pushToast("success", message);
      void queryClient.invalidateQueries({ queryKey: ["jobs", id] });
      void queryClient.invalidateQueries({ queryKey: ["jobs"] });
    },
    onError: (error: Error) => pushToast("error", error.message),
  });

  if (job.isPending) {
    return (
      <main className="grid min-h-[70vh] place-items-center">
        <span className="loading loading-spinner text-primary" />
      </main>
    );
  }
  if (job.isError) {
    return (
      <main className="mx-auto max-w-5xl p-6">
        <div className="alert alert-error">{job.error.message}</div>
      </main>
    );
  }

  const item = job.data;
  const evaluation = item.evaluation;
  const research = item.company_summary;

  return (
    <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <Link className="btn btn-ghost btn-sm -ml-2 mb-4" href="/jobs">
        <ArrowLeft className="size-4" /> Back to jobs
      </Link>
      <div className="flex flex-wrap items-start justify-between gap-5">
        <div>
          <h1 className="text-3xl font-semibold">{item.title}</h1>
          <p className="mt-1 text-lg text-base-content/65">
            {item.company_name} · {item.location}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {item.application_url ? (
            <a
              className="btn btn-outline btn-sm"
              href={item.application_url}
              rel="noreferrer"
              target="_blank"
            >
              Original listing <ExternalLink className="size-4" />
            </a>
          ) : null}
          <button
            className="btn btn-ghost btn-sm"
            disabled={action.isPending}
            onClick={() => action.mutate("dismiss")}
          >
            <X className="size-4" /> Not interested
          </button>
          {evaluation ? (
            <button
              className="btn btn-outline btn-sm"
              disabled={action.isPending}
              onClick={() => action.mutate("evaluate")}
            >
              <RefreshCw className="size-4" /> Re-run evaluation
            </button>
          ) : (
            <button
              className="btn btn-primary btn-sm"
              disabled={action.isPending}
              onClick={() => action.mutate("evaluate")}
            >
              Evaluate now
            </button>
          )}
          {evaluation?.final_classification === "good_fit" ? (
            evaluation.application_doc ? (
              <>
                <button
                  className="btn btn-outline btn-sm"
                  onClick={() => setDocumentsOpen(true)}
                  type="button"
                >
                  <FileText className="size-4" /> View documents
                </button>
                <Link
                  className="btn btn-primary btn-sm"
                  href={`/jobs/${id}/apply`}
                >
                  Prepare application <Send className="size-4" />
                </Link>
              </>
            ) : (
              <button
                className="btn btn-primary btn-sm"
                disabled={action.isPending}
                onClick={() => action.mutate("generate")}
                type="button"
              >
                {action.isPending ? (
                  <span className="loading loading-spinner loading-xs" />
                ) : (
                  <Sparkles className="size-4" />
                )}
                Generate documents
              </button>
            )
          ) : null}
        </div>
      </div>

      <div className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]">
        <div className="space-y-6">
          <section className="rounded-2xl border border-base-300 bg-base-100 p-6">
            <h2 className="text-lg font-semibold">Role description</h2>
            <p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-base-content/80">
              {item.description}
            </p>
            {item.requirements.length ? (
              <ul className="mt-5 list-inside list-disc space-y-2 text-sm">
                {item.requirements.map((requirement) => (
                  <li key={requirement}>{requirement}</li>
                ))}
              </ul>
            ) : null}
          </section>
          {research ? (
            <section className="rounded-2xl border border-base-300 bg-base-100 p-6">
              <h2 className="text-lg font-semibold">Company research</h2>
              <p className="mt-3 text-sm leading-7">{research.ai_summary}</p>
              <dl className="mt-5 grid gap-4 sm:grid-cols-2">
                {[
                  ["Mission", research.mission],
                  ["Values", research.values],
                  ["Culture", research.culture],
                  ["Technology", research.tech_stack],
                  ["Company size", research.team_size_approx],
                  ["Recent developments", research.recent_news],
                ].map(([label, value]) => (
                  <div className="rounded-xl bg-base-200 p-4" key={label}>
                    <dt className="text-xs font-semibold uppercase tracking-wide text-primary">
                      {label}
                    </dt>
                    <dd className="mt-1 text-sm">{value}</dd>
                  </div>
                ))}
              </dl>
              {research.source_urls.length ? (
                <div className="mt-5">
                  <h3 className="text-sm font-semibold">Sources</h3>
                  <ul className="mt-2 space-y-1 text-sm">
                    {research.source_urls.map((url) => (
                      <li key={url}>
                        <a
                          className="link link-primary break-all"
                          href={url}
                          rel="noreferrer"
                          target="_blank"
                        >
                          {url}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </section>
          ) : null}
        </div>
        <aside>
          <section className="sticky top-24 rounded-2xl border border-base-300 bg-base-100 p-6">
            <h2 className="text-lg font-semibold">Fit evaluation</h2>
            {evaluation ? (
              <>
                <div className="mt-4 flex items-center gap-3">
                  <div
                    className="radial-progress text-primary"
                    style={
                      {
                        "--value": evaluation.overall_score * 10,
                      } as React.CSSProperties
                    }
                    role="progressbar"
                  >
                    {evaluation.overall_score.toFixed(1)}
                  </div>
                  <div>
                    <p className="font-semibold">
                      {evaluation.final_classification.replaceAll("_", " ")}
                    </p>
                    <p className="text-xs text-base-content/55">out of 10</p>
                  </div>
                </div>
                <p className="mt-5 text-sm leading-6">
                  {evaluation.final_feedback}
                </p>
                <div className="mt-5 space-y-2">
                  {Object.entries(evaluation.dimension_scores).map(
                    ([key, value]) => (
                      <div
                        className="flex justify-between rounded-lg bg-base-200 px-3 py-2 text-sm"
                        key={key}
                      >
                        <span>{key.replaceAll("_", " ")}</span>
                        <span className="font-semibold">{String(value)}</span>
                      </div>
                    ),
                  )}
                </div>
              </>
            ) : (
              <p className="mt-3 text-sm text-base-content/60">
                Evaluation is pending.
              </p>
            )}
          </section>
        </aside>
      </div>
      {evaluation?.application_doc ? (
        <JobDocumentsModal
          applicationDocument={evaluation.application_doc}
          jobId={id}
          onClose={() => setDocumentsOpen(false)}
          open={documentsOpen}
        />
      ) : null}
    </main>
  );
}
