// frontend/src/app/(auth)/forgot-password/page.tsx
"use client";

import { useMutation } from "@tanstack/react-query";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { forgotPassword } from "@/lib/api/auth";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const request = useMutation({ mutationFn: () => forgotPassword(email) });
  function submit(event: FormEvent): void {
    event.preventDefault();
    request.mutate();
  }
  return (
    <main className="w-full max-w-md rounded-2xl border border-base-300 bg-base-100 p-7 shadow-marketing-card">
      <Link className="text-xl font-bold text-primary" href="/">
        Kaziro
      </Link>
      <h1 className="mt-6 text-2xl font-semibold">Reset your password</h1>
      <p className="mt-2 text-sm text-base-content/65">
        We’ll email you a secure reset link if the account exists.
      </p>
      {request.isSuccess ? (
        <div className="alert alert-success mt-5" role="status">
          {request.data.message}
        </div>
      ) : (
        <form className="mt-5" onSubmit={submit}>
          <label className="form-control">
            <span className="label-text mb-1">Email address</span>
            <input
              className="input input-bordered"
              required
              type="email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
              autoComplete="email"
            />
          </label>
          {request.isError ? (
            <div className="alert alert-error mt-4" role="alert">
              {request.error.message}
            </div>
          ) : null}
          <button
            className="btn btn-primary mt-5 w-full"
            disabled={request.isPending}
            type="submit"
          >
            {request.isPending ? "Sending…" : "Send reset link"}
          </button>
        </form>
      )}
      <Link
        className="link link-primary mt-5 block text-center text-sm"
        href="/login"
      >
        Back to sign in
      </Link>
    </main>
  );
}

// frontend/src/routes/(auth)/forgot-password/+page.svelte
<script lang="ts">
	import { forgotSchema } from '$lib/schemas/auth';
	import { supabase } from '$lib/supabase';
	import Button from '$lib/components/ui/Button.svelte';

	let email = $state('');
	let fieldErrors = $state<Record<string, string>>({});
	let done = $state(false);
	let pending = $state(false);

	async function submit(e: Event): Promise<void> {
		e.preventDefault();
		fieldErrors = {};
		const parsed = forgotSchema.safeParse({ email });
		if (!parsed.success) {
			for (const iss of parsed.error.issues) {
				const k = String(iss.path[0] ?? 'form');
				fieldErrors = { ...fieldErrors, [k]: iss.message };
			}
			return;
		}
		pending = true;
		const { error } = await supabase.auth.resetPasswordForEmail(parsed.data.email, {
			redirectTo: `${typeof window !== 'undefined' ? window.location.origin : ''}/login`
		});
		pending = false;
		if (error) {
			fieldErrors = { ...fieldErrors, email: error.message };
			return;
		}
		done = true;
	}
</script>

<svelte:head>
	<title>Forgot password — Kaziro</title>
</svelte:head>

<h1 class="mb-4 text-xl font-semibold">Reset password</h1>
{#if done}
	<p class="text-sm text-base-content/80">
		If an account exists for that email, you will receive recovery instructions shortly.
	</p>
{:else}
	<form class="space-y-4" onsubmit={submit}>
		<label class="form-control">
			<span class="label-text font-medium">Email</span>
			<input
				class="input input-bordered rounded-xl border-base-300 bg-base-200 {fieldErrors.email
					? 'input-error'
					: ''}"
				type="email"
				autocomplete="email"
				bind:value={email}
			/>
			{#if fieldErrors.email}<span class="label-text-alt text-error">{fieldErrors.email}</span>{/if}
		</label>
		<Button type="submit" disabled={pending}>{pending ? 'Sending…' : 'Send reset link'}</Button>
	</form>
{/if}
<p class="mt-4 text-sm">
	<a class="link font-medium" href="/login">Back to log in</a>
</p>
